default_provider = "protonpass"

[secrets]
GOOGLE_CREDENTIALS = { value = "drive-cli-client-id-and-secret/note", provider = "protonpass" }
#GOOGLE_CREDENTIALS = { value = "drive-nilleb-com-client-id-and-secret/note", provider = "protonpass" }
